# Generated by Django 2.2 on 2019-07-30 07:26

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=market.models.PathAndRename('Categories/2019/07/30', 'Category'), verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=market.models.PathAndRename('Categories/thumbnails/2019/07/30', 'Category'), verbose_name='Thumbnail')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.Category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.PathAndRename('products/2019/07/30', 'Product'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=market.models.PathAndRename('products/thumbnails/2019/07/30', 'Product'), verbose_name='Thumbnail'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='market.Category', verbose_name='Category'),
        ),
    ]
